// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ar_transform_cpp
arma::vec ar_transform_cpp(const arma::vec& x, const arma::vec& phi);
RcppExport SEXP _tstse_ar_transform_cpp(SEXP xSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(ar_transform_cpp(x, phi));
    return rcpp_result_gen;
END_RCPP
}
// co_time_transform_cpp
arma::vec co_time_transform_cpp(int n, const arma::vec& phi);
RcppExport SEXP _tstse_co_time_transform_cpp(SEXP nSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(co_time_transform_cpp(n, phi));
    return rcpp_result_gen;
END_RCPP
}
// backcast_cpp
NumericVector backcast_cpp(NumericVector x, NumericVector phi, NumericVector theta, int n_back);
RcppExport SEXP _tstse_backcast_cpp(SEXP xSEXP, SEXP phiSEXP, SEXP thetaSEXP, SEXP n_backSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n_back(n_backSEXP);
    rcpp_result_gen = Rcpp::wrap(backcast_cpp(x, phi, theta, n_back));
    return rcpp_result_gen;
END_RCPP
}
// burg_aic_select_cpp
Rcpp::List burg_aic_select_cpp(const arma::vec& x, int maxp, std::string criterion, int min_p);
RcppExport SEXP _tstse_burg_aic_select_cpp(SEXP xSEXP, SEXP maxpSEXP, SEXP criterionSEXP, SEXP min_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type maxp(maxpSEXP);
    Rcpp::traits::input_parameter< std::string >::type criterion(criterionSEXP);
    Rcpp::traits::input_parameter< int >::type min_p(min_pSEXP);
    rcpp_result_gen = Rcpp::wrap(burg_aic_select_cpp(x, maxp, criterion, min_p));
    return rcpp_result_gen;
END_RCPP
}
// burg_fit_cpp
arma::vec burg_fit_cpp(const arma::vec& x, int p);
RcppExport SEXP _tstse_burg_fit_cpp(SEXP xSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(burg_fit_cpp(x, p));
    return rcpp_result_gen;
END_RCPP
}
// co_tas_cpp
Rcpp::List co_tas_cpp(const arma::vec& x, int maxp, std::string type);
RcppExport SEXP _tstse_co_tas_cpp(SEXP xSEXP, SEXP maxpSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type maxp(maxpSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(co_tas_cpp(x, maxp, type));
    return rcpp_result_gen;
END_RCPP
}
// co_tstat_cpp
double co_tstat_cpp(const arma::vec& x, int maxp, std::string criterion);
RcppExport SEXP _tstse_co_tstat_cpp(SEXP xSEXP, SEXP maxpSEXP, SEXP criterionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type maxp(maxpSEXP);
    Rcpp::traits::input_parameter< std::string >::type criterion(criterionSEXP);
    rcpp_result_gen = Rcpp::wrap(co_tstat_cpp(x, maxp, criterion));
    return rcpp_result_gen;
END_RCPP
}
// co_full_cpp
Rcpp::List co_full_cpp(const arma::vec& x, int maxp, std::string criterion);
RcppExport SEXP _tstse_co_full_cpp(SEXP xSEXP, SEXP maxpSEXP, SEXP criterionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type maxp(maxpSEXP);
    Rcpp::traits::input_parameter< std::string >::type criterion(criterionSEXP);
    rcpp_result_gen = Rcpp::wrap(co_full_cpp(x, maxp, criterion));
    return rcpp_result_gen;
END_RCPP
}
// ols_detrend_cpp
arma::vec ols_detrend_cpp(const arma::vec& x);
RcppExport SEXP _tstse_ols_detrend_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ols_detrend_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// co_tas_boot_kernel_cpp
Rcpp::NumericVector co_tas_boot_kernel_cpp(int n, const arma::vec& phi, double vara, const std::vector<uint64_t>& seeds, int maxp, std::string type, std::size_t grain_size);
RcppExport SEXP _tstse_co_tas_boot_kernel_cpp(SEXP nSEXP, SEXP phiSEXP, SEXP varaSEXP, SEXP seedsSEXP, SEXP maxpSEXP, SEXP typeSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type vara(varaSEXP);
    Rcpp::traits::input_parameter< const std::vector<uint64_t>& >::type seeds(seedsSEXP);
    Rcpp::traits::input_parameter< int >::type maxp(maxpSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(co_tas_boot_kernel_cpp(n, phi, vara, seeds, maxp, type, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// co_tas_boot_tstat_kernel_cpp
Rcpp::NumericVector co_tas_boot_tstat_kernel_cpp(int n, const arma::vec& phi, double vara, const std::vector<uint64_t>& seeds, int maxp, std::string type, std::size_t grain_size);
RcppExport SEXP _tstse_co_tas_boot_tstat_kernel_cpp(SEXP nSEXP, SEXP phiSEXP, SEXP varaSEXP, SEXP seedsSEXP, SEXP maxpSEXP, SEXP typeSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type vara(varaSEXP);
    Rcpp::traits::input_parameter< const std::vector<uint64_t>& >::type seeds(seedsSEXP);
    Rcpp::traits::input_parameter< int >::type maxp(maxpSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(co_tas_boot_tstat_kernel_cpp(n, phi, vara, seeds, maxp, type, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// co_tstat_pure_cpp
double co_tstat_pure_cpp(const arma::vec& x, int maxp, std::string criterion, int min_p);
RcppExport SEXP _tstse_co_tstat_pure_cpp(SEXP xSEXP, SEXP maxpSEXP, SEXP criterionSEXP, SEXP min_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type maxp(maxpSEXP);
    Rcpp::traits::input_parameter< std::string >::type criterion(criterionSEXP);
    Rcpp::traits::input_parameter< int >::type min_p(min_pSEXP);
    rcpp_result_gen = Rcpp::wrap(co_tstat_pure_cpp(x, maxp, criterion, min_p));
    return rcpp_result_gen;
END_RCPP
}
// gen_ar_seeded_cpp
arma::vec gen_ar_seeded_cpp(int n, const arma::vec& phi, double vara, uint64_t rng_seed);
RcppExport SEXP _tstse_gen_ar_seeded_cpp(SEXP nSEXP, SEXP phiSEXP, SEXP varaSEXP, SEXP rng_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type vara(varaSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type rng_seed(rng_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(gen_ar_seeded_cpp(n, phi, vara, rng_seed));
    return rcpp_result_gen;
END_RCPP
}
// wbg_bootstrap_kernel_grain_cpp
Rcpp::NumericVector wbg_bootstrap_kernel_grain_cpp(int n, const arma::vec& phi, double vara, const std::vector<uint64_t>& seeds, int maxp, std::string criterion, std::size_t grain_size, int min_p);
RcppExport SEXP _tstse_wbg_bootstrap_kernel_grain_cpp(SEXP nSEXP, SEXP phiSEXP, SEXP varaSEXP, SEXP seedsSEXP, SEXP maxpSEXP, SEXP criterionSEXP, SEXP grain_sizeSEXP, SEXP min_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type vara(varaSEXP);
    Rcpp::traits::input_parameter< const std::vector<uint64_t>& >::type seeds(seedsSEXP);
    Rcpp::traits::input_parameter< int >::type maxp(maxpSEXP);
    Rcpp::traits::input_parameter< std::string >::type criterion(criterionSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type grain_size(grain_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type min_p(min_pSEXP);
    rcpp_result_gen = Rcpp::wrap(wbg_bootstrap_kernel_grain_cpp(n, phi, vara, seeds, maxp, criterion, grain_size, min_p));
    return rcpp_result_gen;
END_RCPP
}
// wbg_bootstrap_coba_kernel_grain_cpp
Rcpp::List wbg_bootstrap_coba_kernel_grain_cpp(int n, const arma::vec& phi, double vara, const std::vector<uint64_t>& seeds, int maxp, std::string criterion, std::size_t grain_size, int min_p);
RcppExport SEXP _tstse_wbg_bootstrap_coba_kernel_grain_cpp(SEXP nSEXP, SEXP phiSEXP, SEXP varaSEXP, SEXP seedsSEXP, SEXP maxpSEXP, SEXP criterionSEXP, SEXP grain_sizeSEXP, SEXP min_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type vara(varaSEXP);
    Rcpp::traits::input_parameter< const std::vector<uint64_t>& >::type seeds(seedsSEXP);
    Rcpp::traits::input_parameter< int >::type maxp(maxpSEXP);
    Rcpp::traits::input_parameter< std::string >::type criterion(criterionSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type grain_size(grain_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type min_p(min_pSEXP);
    rcpp_result_gen = Rcpp::wrap(wbg_bootstrap_coba_kernel_grain_cpp(n, phi, vara, seeds, maxp, criterion, grain_size, min_p));
    return rcpp_result_gen;
END_RCPP
}
// convolve_truncated_cpp
NumericVector convolve_truncated_cpp(NumericVector C1, NumericVector C2, int n);
RcppExport SEXP _tstse_convolve_truncated_cpp(SEXP C1SEXP, SEXP C2SEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type C1(C1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_truncated_cpp(C1, C2, n));
    return rcpp_result_gen;
END_RCPP
}
// gegenb_cpp
NumericVector gegenb_cpp(double u, double d, int n_coef);
RcppExport SEXP _tstse_gegenb_cpp(SEXP uSEXP, SEXP dSEXP, SEXP n_coefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type n_coef(n_coefSEXP);
    rcpp_result_gen = Rcpp::wrap(gegenb_cpp(u, d, n_coef));
    return rcpp_result_gen;
END_RCPP
}
// gen_arch_cpp
NumericVector gen_arch_cpp(int n, double alpha0, NumericVector alpha, int spin, Nullable<int> seed);
RcppExport SEXP _tstse_gen_arch_cpp(SEXP nSEXP, SEXP alpha0SEXP, SEXP alphaSEXP, SEXP spinSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type spin(spinSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(gen_arch_cpp(n, alpha0, alpha, spin, seed));
    return rcpp_result_gen;
END_RCPP
}
// gen_garch_cpp
NumericVector gen_garch_cpp(int n, double alpha0, NumericVector alpha, NumericVector beta, int spin, Nullable<int> seed);
RcppExport SEXP _tstse_gen_garch_cpp(SEXP nSEXP, SEXP alpha0SEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP spinSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type spin(spinSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(gen_garch_cpp(n, alpha0, alpha, beta, spin, seed));
    return rcpp_result_gen;
END_RCPP
}
// sen_slope_cpp
double sen_slope_cpp(NumericVector x);
RcppExport SEXP _tstse_sen_slope_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sen_slope_cpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tstse_ar_transform_cpp", (DL_FUNC) &_tstse_ar_transform_cpp, 2},
    {"_tstse_co_time_transform_cpp", (DL_FUNC) &_tstse_co_time_transform_cpp, 2},
    {"_tstse_backcast_cpp", (DL_FUNC) &_tstse_backcast_cpp, 4},
    {"_tstse_burg_aic_select_cpp", (DL_FUNC) &_tstse_burg_aic_select_cpp, 4},
    {"_tstse_burg_fit_cpp", (DL_FUNC) &_tstse_burg_fit_cpp, 2},
    {"_tstse_co_tas_cpp", (DL_FUNC) &_tstse_co_tas_cpp, 3},
    {"_tstse_co_tstat_cpp", (DL_FUNC) &_tstse_co_tstat_cpp, 3},
    {"_tstse_co_full_cpp", (DL_FUNC) &_tstse_co_full_cpp, 3},
    {"_tstse_ols_detrend_cpp", (DL_FUNC) &_tstse_ols_detrend_cpp, 1},
    {"_tstse_co_tas_boot_kernel_cpp", (DL_FUNC) &_tstse_co_tas_boot_kernel_cpp, 7},
    {"_tstse_co_tas_boot_tstat_kernel_cpp", (DL_FUNC) &_tstse_co_tas_boot_tstat_kernel_cpp, 7},
    {"_tstse_co_tstat_pure_cpp", (DL_FUNC) &_tstse_co_tstat_pure_cpp, 4},
    {"_tstse_gen_ar_seeded_cpp", (DL_FUNC) &_tstse_gen_ar_seeded_cpp, 4},
    {"_tstse_wbg_bootstrap_kernel_grain_cpp", (DL_FUNC) &_tstse_wbg_bootstrap_kernel_grain_cpp, 8},
    {"_tstse_wbg_bootstrap_coba_kernel_grain_cpp", (DL_FUNC) &_tstse_wbg_bootstrap_coba_kernel_grain_cpp, 8},
    {"_tstse_convolve_truncated_cpp", (DL_FUNC) &_tstse_convolve_truncated_cpp, 3},
    {"_tstse_gegenb_cpp", (DL_FUNC) &_tstse_gegenb_cpp, 3},
    {"_tstse_gen_arch_cpp", (DL_FUNC) &_tstse_gen_arch_cpp, 5},
    {"_tstse_gen_garch_cpp", (DL_FUNC) &_tstse_gen_garch_cpp, 6},
    {"_tstse_sen_slope_cpp", (DL_FUNC) &_tstse_sen_slope_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_tstse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
