// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// backcast_cpp
NumericVector backcast_cpp(NumericVector x, NumericVector phi, NumericVector theta, int n_back);
RcppExport SEXP _tstse_backcast_cpp(SEXP xSEXP, SEXP phiSEXP, SEXP thetaSEXP, SEXP n_backSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n_back(n_backSEXP);
    rcpp_result_gen = Rcpp::wrap(backcast_cpp(x, phi, theta, n_back));
    return rcpp_result_gen;
END_RCPP
}
// convolve_truncated_cpp
NumericVector convolve_truncated_cpp(NumericVector C1, NumericVector C2, int n);
RcppExport SEXP _tstse_convolve_truncated_cpp(SEXP C1SEXP, SEXP C2SEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type C1(C1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_truncated_cpp(C1, C2, n));
    return rcpp_result_gen;
END_RCPP
}
// gegenb_cpp
NumericVector gegenb_cpp(double u, double d, int n_coef);
RcppExport SEXP _tstse_gegenb_cpp(SEXP uSEXP, SEXP dSEXP, SEXP n_coefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type n_coef(n_coefSEXP);
    rcpp_result_gen = Rcpp::wrap(gegenb_cpp(u, d, n_coef));
    return rcpp_result_gen;
END_RCPP
}
// gen_arch_cpp
NumericVector gen_arch_cpp(int n, double alpha0, NumericVector alpha, int spin, Nullable<int> seed);
RcppExport SEXP _tstse_gen_arch_cpp(SEXP nSEXP, SEXP alpha0SEXP, SEXP alphaSEXP, SEXP spinSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type spin(spinSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(gen_arch_cpp(n, alpha0, alpha, spin, seed));
    return rcpp_result_gen;
END_RCPP
}
// gen_garch_cpp
NumericVector gen_garch_cpp(int n, double alpha0, NumericVector alpha, NumericVector beta, int spin, Nullable<int> seed);
RcppExport SEXP _tstse_gen_garch_cpp(SEXP nSEXP, SEXP alpha0SEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP spinSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type spin(spinSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(gen_garch_cpp(n, alpha0, alpha, beta, spin, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tstse_backcast_cpp", (DL_FUNC) &_tstse_backcast_cpp, 4},
    {"_tstse_convolve_truncated_cpp", (DL_FUNC) &_tstse_convolve_truncated_cpp, 3},
    {"_tstse_gegenb_cpp", (DL_FUNC) &_tstse_gegenb_cpp, 3},
    {"_tstse_gen_arch_cpp", (DL_FUNC) &_tstse_gen_arch_cpp, 5},
    {"_tstse_gen_garch_cpp", (DL_FUNC) &_tstse_gen_garch_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_tstse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
