# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Backcast residuals (C++ implementation)
#'
#' @param x Numeric vector, the time series.
#' @param phi Numeric vector, AR coefficients.
#' @param theta Numeric vector, MA coefficients.
#' @param n_back Integer, how far back to backcast.
#' @return Numeric vector of residuals.
#' @keywords internal
#' @noRd
backcast_cpp <- function(x, phi, theta, n_back = 50L) {
    .Call(`_tstse_backcast_cpp`, x, phi, theta, n_back)
}

#' Truncated Polynomial Convolution (C++ implementation)
#'
#' Computes the first n coefficients of the product of two power series.
#' Used for multiplying Gegenbauer polynomial coefficient sequences.
#'
#' @param C1 NumericVector, first coefficient sequence.
#' @param C2 NumericVector, second coefficient sequence.
#' @param n Integer, number of output coefficients.
#' @return NumericVector of length n containing convolution result.
#' @keywords internal
#' @noRd
convolve_truncated_cpp <- function(C1, C2, n) {
    .Call(`_tstse_convolve_truncated_cpp`, C1, C2, n)
}

#' Gegenbauer Polynomial Coefficients (C++ implementation)
#'
#' Computes the coefficients C_k(d, u) using the recurrence relation.
#' This is the internal C++ implementation called by the R wrapper.
#'
#' @param u Numeric scalar, cosine of the Gegenbauer frequency.
#' @param d Numeric scalar, long-memory parameter.
#' @param n_coef Integer, number of coefficients to compute.
#' @return NumericVector of length n_coef containing C_0, C_1, ..., C_{n-1}.
#' @keywords internal
#' @noRd
gegenb_cpp <- function(u, d, n_coef) {
    .Call(`_tstse_gegenb_cpp`, u, d, n_coef)
}

gen_arch_cpp <- function(n, alpha0, alpha, spin = 1000L, seed = NULL) {
    .Call(`_tstse_gen_arch_cpp`, n, alpha0, alpha, spin, seed)
}

gen_garch_cpp <- function(n, alpha0, alpha, beta, spin = 1000L, seed = NULL) {
    .Call(`_tstse_gen_garch_cpp`, n, alpha0, alpha, beta, spin, seed)
}

